---
apiVersion: v1
kind: Pod
metadata:
  name: web-sample-otvl
  labels:
    app.kubernetes.io/name: web-sample-otvl
spec:
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
  containers:
    - name: web-server
      image: nginxinc/nginx-unprivileged:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: workdir
          subPath: code/k8s-manifests-to-helm-steps/html
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: install
      image: bitnami/git
      command:
        - git
        - clone
        - --single-branch
        - --branch
        - bdev4
        - --
        - https://github.com/t-beigbeder/otvl_blog
        - /workdir
      volumeMounts:
        - name: workdir
          mountPath: /workdir
  volumes:
    - name: workdir
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: web-sample-otvl
spec:
  selector:
    app.kubernetes.io/name: web-sample-otvl
  ports:
      - name: "wev-port"
        port: 8080
        protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-sample-otvl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - web-sample-otvl.example.com
      secretName: web-sample-otvl
  rules:
    - host: web-sample-otvl.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  web-sample-otvl
                port:
                  number: 8080
