apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Release.Name }}.example.com
      secretName: {{ .Release.Name }}
  rules:
    - host: {{ .Release.Name }}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ .Release.Name }}
                port:
                  number: 8080
