apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: thierry@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: v1
kind: Pod
metadata:
  name: http-echo-1
  labels:
    app.kubernetes.io/name: http-echo-1
spec:
  containers:
    - name: echo
      image: mendhak/http-https-echo
      ports:
        - containerPort: 8080

  restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-1
spec:
  selector:
    app.kubernetes.io/name: http-echo-1
  ports:
    - name: "echo-port"
      port: 8080
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: http-echo-2
  labels:
    app.kubernetes.io/name: http-echo-2
spec:
  containers:
    - name: echo
      image: mendhak/http-https-echo
      ports:
        - containerPort: 8080

  restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-2
spec:
  selector:
    app.kubernetes.io/name: http-echo-2
  ports:
    - name: "echo-port"
      port: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-echo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - site.tp.example.com
        - api.tp.example.com
      secretName: http-echo
  rules:
    - host: site.tp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  http-echo-1
                port:
                  number: 8080
    - host: api.tp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  http-echo-2
                port:
                  number: 8080
